// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZGVAkO-lT6Xg2rBgGjQwDnIZgx_ENL9w',
    appId: '1:913773600786:web:8ed2cb82bf0445f899f8cb',
    messagingSenderId: '913773600786',
    projectId: 'lockly-11e99',
    authDomain: 'lockly-11e99.firebaseapp.com',
    storageBucket: 'lockly-11e99.firebasestorage.app',
    measurementId: 'G-C0PJ01NKJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiaWj2pbobOs71ZUaCpM82xbRQITgltA4',
    appId: '1:913773600786:android:b65640204844fb5199f8cb',
    messagingSenderId: '913773600786',
    projectId: 'lockly-11e99',
    storageBucket: 'lockly-11e99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrYe25p-tMdLKjFNtfDfRDbgUOKfSlvfA',
    appId: '1:913773600786:ios:1b15fbabb6848ada99f8cb',
    messagingSenderId: '913773600786',
    projectId: 'lockly-11e99',
    storageBucket: 'lockly-11e99.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrYe25p-tMdLKjFNtfDfRDbgUOKfSlvfA',
    appId: '1:913773600786:ios:1b15fbabb6848ada99f8cb',
    messagingSenderId: '913773600786',
    projectId: 'lockly-11e99',
    storageBucket: 'lockly-11e99.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZGVAkO-lT6Xg2rBgGjQwDnIZgx_ENL9w',
    appId: '1:913773600786:web:346bc20c0d08290c99f8cb',
    messagingSenderId: '913773600786',
    projectId: 'lockly-11e99',
    authDomain: 'lockly-11e99.firebaseapp.com',
    storageBucket: 'lockly-11e99.firebasestorage.app',
    measurementId: 'G-9P8EKWLZ7P',
  );
}
